### ISSUE TITLE
Adding support for Android 2.1 and 2.2

### ISSUE THREAD

**Issue by trietbui85** [sephiroth74/AndroidWheel#1]
Your wheel looks great & funny.
But, I must set API to >= 9 when build because in Wheel.java line 1084 you define a OverScroller (which only from API 9+). This mean I cannot run this app on Android 2.1 and 2.2.

Can you take time to add support for 2.1 and 2.2?

Thanks.

**Comment by sephiroth74** [comment]
It already supports android 2.2. You just have to set as target sdk 9, but minSdk 8.
If you look at the line 201 there's a switch based on the android sdk version.
