### ISSUE TITLE
Error importing android wheel to my project

### ISSUE THREAD

**Issue by bamsbamx** [sephiroth74/AndroidWheel#2]
Hey there! I just imported this project to Eclipse to use it as library, but when I added this library to my project, a lot of errors appeared suddenly in my project... Errors were  like this: R cannot be resolved to a variable. So, which is the correct way to import android wheel?

**Comment by sephiroth74** [comment]
Is your project build target for android-15? check out that your project has the same build target. Otherwise in many cases it's just a matter of cleaning up projects in eclipse

**Comment by bamsbamx** [comment]
Thanks for the quick reply!!! It seemed to work well, but now i have another two problems, both come from the same file: No resource identifier found for attribute numRotations in package it.sephiroth.android.wheel
. Same for ticks.. The file is AndroidWheel/res/layout/wheel_panel.xml:5 1 ...min sdk8 target sdk 15 hope you can help me... Thanks again!

**Comment by sephiroth74** [comment]
yes, it's an old adt bug.
checkout this: http://code.google.com/p/android/issues/detail?id=9656
in the wheel_panel.xml try to change in the xmlns schemas from "http://schemas.android.com/apk/res/it.sephiroth.android.wheel" into "http://schemas.android.com/apk/res-auto" ( 2 occurrences )

**Comment by bamsbamx** [comment]
ok, changed it, but problem persists, in addition in my project all things related to R have errors... Should i delete "import it.sephiroth.android.wheel.R;" from your files????

**Comment by bamsbamx** [comment]
tried this 
<LinearLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:sephiroth="http://schemas.android.com/apk/res-auto"
    ....

but not success :( any solution please???

**Comment by bamsbamx** [comment]
and i have watched that R.java is not created inside my project

**Comment by sephiroth74** [comment]
checkout the demo app I uploaded here: https://github.com/sephiroth74/AndroidWheel/downloads
The "TestWheel" project is using AndroidWheel as library project.
